In [2]:
"""終値を格納する"""
import datetime

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas_datareader
import sklearn
import sklearn.linear_model
import sklearn.model_selection
import yfinance

yfinance.pdr_override()

df_aapl = pandas_datareader.data.get_data_yahoo('AAPL', '2020-01-01')

df_aapl['changing'] = (((df_aapl['Close'] - df_aapl['Open'])) / (df_aapl['Open']) * 100)
df_aapl ['label'] = df_aapl['Close'].shift(-30)
df_aapl.tail(35)

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,changing,label
Date,,,,,,,,
2022-12-06,147.070007,147.300003,141.919998,142.910004,142.910004,64727200,-2.828587,137.869995
2022-12-07,142.190002,143.369995,140.000000,140.940002,140.940002,69721100,-0.879105,141.110001
2022-12-08,142.360001,143.520004,141.100006,142.649994,142.649994,62128300,0.203704,142.529999
2022-12-09,142.339996,145.570007,140.899994,142.160004,142.160004,76097000,-0.126453,141.860001
2022-12-12,142.699997,144.500000,141.059998,144.490005,144.490005,70462700,1.254386,143.960007
2022-12-13,149.500000,149.970001,144.240005,145.470001,145.470001,93886200,-2.695651,NaN
2022-12-14,145.350006,146.660004,141.160004,143.210007,143.210007,82291200,-1.472308,NaN
2022-12-15,141.110001,141.800003,136.029999,136.500000,136.500000,98931900,-3.266955,NaN
2022-12-16,136.690002,137.649994,133.729996,134.509995,134.509995,160156900,-1.594855,NaN
2022-12-19,135.110001,135.199997,131.320007,132.369995,132.369995,79592600,-2.027981,NaN
2022-12-20,131.389999,133.250000,129.889999,132.300003,132.300003,77432800,0.692597,NaN
2022-12-21,132.979996,136.809998,132.750000,135.449997,135.449997,85928000,1.857423,NaN
2022-12-22,134.350006,134.559998,130.300003,132.229996,132.229996,77852100,-1.577976,NaN
2022-12-23,130.919998,132.419998,129.639999,131.860001,131.860001,63814900,0.717998,NaN
2022-12-27,131.380005,131.410004,128.720001,130.029999,130.029999,69007800,-1.027558,NaN
2022-12-28,129.669998,131.029999,125.870003,126.040001,126.040001,85438400,-2.799412,NaN
2022-12-29,127.989998,130.479996,127.730003,129.610001,129.610001,75703700,1.265726,NaN
2022-12-30,128.410004,129.949997,127.430000,129.929993,129.929993,76960600,1.183700,NaN
2023-01-03,130.279999,130.899994,124.169998,125.070000,125.070000,112117500,-3.999078,NaN
2023-01-04,126.889999,128.660004,125.080002,126.360001,126.360001,89113600,-0.417684,NaN
2023-01-05,127.129997,127.769997,124.760002,125.019997,125.019997,80962700,-1.659719,NaN
2023-01-06,126.010002,130.289993,124.889999,129.619995,129.619995,87686600,2.864846,NaN
2023-01-09,130.470001,133.410004,129.889999,130.149994,130.149994,70790800,-0.245273,NaN
2023-01-10,130.259995,131.259995,128.119995,130.729996,130.729996,63896200,0.360818,NaN
2023-01-11,131.250000,133.509995,130.460007,133.490005,133.490005,69458900,1.706671,NaN
2023-01-12,133.880005,134.259995,131.440002,133.410004,133.410004,71379600,-0.351062,NaN
2023-01-13,132.029999,134.919998,131.660004,134.759995,134.759995,57758000,2.067709,NaN
2023-01-17,134.830002,137.289993,134.130005,135.940002,135.940002,63646600,0.823259,NaN
2023-01-18,136.820007,138.610001,135.029999,135.210007,135.210007,69672800,-1.176729,NaN
2023-01-19,134.080002,136.250000,133.770004,135.270004,135.270004,58280400,0.887532,NaN
2023-01-20,135.279999,138.020004,134.220001,137.869995,137.869995,79972200,1.914545,NaN
2023-01-23,138.119995,143.320007,137.899994,141.110001,141.110001,81760300,2.164788,NaN
2023-01-24,140.309998,143.160004,140.300003,142.529999,142.529999,66435100,1.582212,NaN
2023-01-25,140.889999,142.429993,138.809998,141.860001,141.860001,65799300,0.688481,NaN
2023-01-26,143.169998,144.250000,141.899994,143.960007,143.960007,54003800,0.551798,NaN